source 'https://rubygems.org'

gem 'rails', '4.0.0'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.0'
gem 'haml-rails'
gem 'uglifier', '>= 1.3.0'
gem 'jquery-rails'
gem 'coffee-rails', '~> 4.0.0'
gem 'angularjs-rails', '~> 1.0.8'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'
gem 'unicorn'
gem 'devise', '~> 3.1.0'
gem 'bootstrap-sass', '~> 2.3.2.2'
gem 'filepicker-rails'

group :development, :test do
  gem 'pry'
  gem 'guard-coffeescript', '~> 1.3.2'
  gem 'guard-jasmine', '~> 1.18.0'
  gem 'jasmine-rails', '~> 0.4.5'
  gem 'rspec-rails'
  gem 'factory_girl_rails'
end